apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tqs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5000/tqsrec-frontend:latest
        imagePullPolicy: Always
        env:
          - name: APP_BACKEND_URL
            value: "http://shop-svc.tqs.svc.cluster.local:8080/api"
          - name: ELASTIC_APM_SERVER_URL
            value: "http://apm.observability.svc.cluster.local:8200"
          - name: ELASTIC_APM_SERVICE_NAME
            value: "frontend"
          - name: ELASTIC_APM_ENVIRONMENT
            value: "production"
        resources:
          limits:
            memory: "5Gi"
            cpu: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: tqs
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
