apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  namespace: tqs
spec:
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: localhost:5000/tqsrec-shop:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_URL
            value: "jdbc:mysql://mysql.mysql.svc.cluster.local:3306/tqsproject"
          - name: PICKY_URL
            value: "http://picky-svc.tqs.svc.cluster.local:8000"
          - name: ES_APM_URL
            value: "http://apm.observability.svc.cluster.local:8200"
        resources:
          limits:
            memory: "5Gi"
            cpu: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: tqs
spec:
  selector:
    app: shop
  ports:
  - port: 8080
    targetPort: 8080
